// Builds the body-map zone masks (WO5 / WO6) from zones.spec.json.
//
//   node scripts/body-zones/build.mjs <assetsDir> [--preview <dir>]
//
// For each figure: its silhouette mask, split into cells by its own line art
// (segment.mjs), plus the spec's CUTS — short lines drawn along that figure's
// own creases (wrist, ankle, waist) where a stroke leaves a gap that would
// join two muscles. A zone is every cell containing one of its SEEDS; wall
// pixels go to the nearest cell, so zones meet under the line art with no
// gap and no overlap, and never leave the silhouette.
//
// Writes public/body/<figure>.png (line art), public/body/zones/<figure>-<zone>.png
// (white = zone, on transparent) and src/data/bodyZones.ts.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { encodePng } from "./png.mjs";
import { loadFigure, segment, fillGaps } from "./segment.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const [, , assets, flag, previewDir] = process.argv;
const spec = JSON.parse(readFileSync(join(here, "zones.spec.json"), "utf8"));

/** Burns a cut line into the line art as an opaque 2px stroke. */
function burnCut(fig, [[x0, y0], [x1, y1]]) {
  const steps = Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2);
  for (let s = 0; s <= steps; s++) {
    const x = Math.round(x0 + ((x1 - x0) * s) / steps);
    const y = Math.round(y0 + ((y1 - y0) * s) / steps);
    for (const [dx, dy] of [[0, 0], [1, 0], [0, 1]]) {
      const i = ((y + dy) * fig.width + (x + dx)) * 4;
      fig.art[i + 3] = 255;
    }
  }
}

mkdirSync(join(root, "public", "body", "zones"), { recursive: true });
if (flag === "--preview") mkdirSync(previewDir, { recursive: true });
const manifest = {};

for (const [key, figSpec] of Object.entries(spec.figures)) {
  copyFileSync(join(assets, `${key}.png`), join(root, "public", "body", `${key}.png`));
  const fig = loadFigure(assets, key);
  for (const cut of figSpec.cuts ?? []) burnCut(fig, cut);
  const seg = segment(fig);
  const owner = fillGaps(seg);
  const zoneOfCell = new Map();
  for (const [zone, z] of Object.entries(figSpec.zones)) {
    for (const [x, y] of z.seeds) {
      const cell = seg.label[y * seg.W + x];
      if (cell === -1) throw new Error(`${key}/${zone}: seed ${x},${y} is on a wall or outside the silhouette`);
      if (zoneOfCell.has(cell) && zoneOfCell.get(cell) !== zone)
        throw new Error(`${key}: cell ${cell} claimed by ${zoneOfCell.get(cell)} and ${zone}`);
      zoneOfCell.set(cell, zone);
    }
  }
  manifest[key] = { width: seg.W, height: seg.H, zones: {} };
  const preview = Buffer.alloc(seg.W * seg.H * 4);
  const zoneNames = Object.keys(figSpec.zones);
  for (const zone of zoneNames) {
    const data = Buffer.alloc(seg.W * seg.H * 4);
    let area = 0;
    let minX = seg.W, minY = seg.H, maxX = 0, maxY = 0;
    for (let i = 0; i < seg.W * seg.H; i++) {
      if (owner[i] !== -1 && zoneOfCell.get(owner[i]) === zone) {
        data[i * 4] = data[i * 4 + 1] = data[i * 4 + 2] = data[i * 4 + 3] = 255;
        area++;
        const x = i % seg.W, y = (i / seg.W) | 0;
        if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y;
        const h = zoneNames.indexOf(zone);
        preview[i * 4] = [230, 90, 60, 250, 120, 40, 200][h % 7];
        preview[i * 4 + 1] = [80, 200, 120, 190, 60, 160, 120][h % 7];
        preview[i * 4 + 2] = [80, 90, 230, 60, 220, 200, 40][h % 7];
        preview[i * 4 + 3] = 170;
      }
    }
    if (area === 0) throw new Error(`${key}/${zone}: empty`);
    writeFileSync(join(root, "public", "body", "zones", `${key}-${zone}.png`), encodePng({ width: seg.W, height: seg.H, data }));
    manifest[key].zones[zone] = {
      source: figSpec.zones[zone].source,
      // The zone's centre, as % of the figure: where its hit label sits.
      cx: +(((minX + maxX) / 2 / seg.W) * 100).toFixed(1),
      cy: +(((minY + maxY) / 2 / seg.H) * 100).toFixed(1),
    };
  }
  if (flag === "--preview") {
    for (let i = 0; i < seg.W * seg.H; i++) if (fig.art[i * 4 + 3] > 40) { preview[i * 4 + 3] = 255; preview[i * 4] = preview[i * 4 + 1] = preview[i * 4 + 2] = 30; }
    writeFileSync(join(previewDir, `${key}-zones.png`), encodePng({ width: seg.W, height: seg.H, data: preview }));
  }
  console.log(key, Object.entries(manifest[key].zones).map(([z, v]) => `${z}:${v.source}`).join(" "));
}

// --- src/data/bodyZones.ts ---------------------------------------------------
const derived = [];
for (const [key, f] of Object.entries(manifest))
  for (const [zone, z] of Object.entries(f.zones)) if (z.source === "derived") derived.push(`${key}/${zone}`);

const ts = `// GENERATED by scripts/body-zones/build.mjs from scripts/body-zones/zones.spec.json.
// Do not edit by hand: change the spec (seeds, cuts) and run the script.
//
// Handover 2026-09-29 WO5 / WO6 body maps. Each figure has its own zone map,
// traced from its own line art and clipped to its own silhouette mask (never
// reused or scaled from another figure). A zone's shape is
// /body/zones/<figure>-<zone>.png: white where the zone is, transparent
// elsewhere, the same size as the figure's line art.
//
// SOURCE: "frame" zones are the shapes an approved frame shows (WO5.3 / WO6.3
// male; the two zones each of WO5.4, WO5.5, WO6.4, WO6.5). "derived" zones
// are NOT in any frame: they were traced by the developer from that figure's
// drawn muscle contours, for the designer to review or replace. All of them
// are listed in DERIVED_BODY_ZONES below.

export type FigureKey = ${Object.keys(manifest).map((k) => JSON.stringify(k)).join(" | ")};
export type ZoneKey =
  | "shoulders" | "chest" | "back" | "biceps" | "triceps" | "forearms"
  | "core" | "glutes" | "quads" | "hamstrings" | "calves";

export interface ZoneShape {
  source: "frame" | "derived";
  /** The zone's centre as % of the figure (x, y). */
  cx: number;
  cy: number;
}

export const BODY_FIGURES: Record<FigureKey, { width: number; height: number; zones: Partial<Record<ZoneKey, ZoneShape>> }> = ${JSON.stringify(manifest, null, 2)};

/** Every zone traced by the developer rather than taken from a frame: for design review. */
export const DERIVED_BODY_ZONES: string[] = ${JSON.stringify(derived, null, 2)};

export const zoneMaskUrl = (figure: FigureKey, zone: ZoneKey) => \`/body/zones/\${figure}-\${zone}.png\`;
`;
writeFileSync(join(root, "src", "data", "bodyZones.ts"), ts);
console.log("derived:", derived.length);
