// GENERATED by scripts/body-zones/build.mjs from scripts/body-zones/zones.spec.json.
// Do not edit by hand: change the spec (seeds, cuts) and run the script.
//
// Handover 2026-09-29 WO5 / WO6 body maps. Each figure has its own zone map,
// traced from its own line art and clipped to its own silhouette mask (never
// reused or scaled from another figure). A zone's shape is
// /body/zones/<figure>-<zone>.png: white where the zone is, transparent
// elsewhere, the same size as the figure's line art.
//
// SOURCE: "frame" zones are the shapes an approved frame shows (WO5.3 / WO6.3
// male; the two zones each of WO5.4, WO5.5, WO6.4, WO6.5). "derived" zones
// are NOT in any frame: they were traced by the developer from that figure's
// drawn muscle contours, for the designer to review or replace. All of them
// are listed in DERIVED_BODY_ZONES below.

export type FigureKey = "male-front" | "male-back" | "female-front" | "female-back" | "andro-front" | "andro-back";
export type ZoneKey =
  | "shoulders" | "chest" | "back" | "biceps" | "triceps" | "forearms"
  | "core" | "glutes" | "quads" | "hamstrings" | "calves";

export interface ZoneShape {
  source: "frame" | "derived";
  /** The zone's centre as % of the figure (x, y). */
  cx: number;
  cy: number;
}

export const BODY_FIGURES: Record<FigureKey, { width: number; height: number; zones: Partial<Record<ZoneKey, ZoneShape>> }> = {
  "male-front": {
    "width": 400,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "frame",
        "cx": 51,
        "cy": 22.9
      },
      "chest": {
        "source": "frame",
        "cx": 51,
        "cy": 24.5
      },
      "biceps": {
        "source": "frame",
        "cx": 50.6,
        "cy": 32
      },
      "forearms": {
        "source": "frame",
        "cx": 50.4,
        "cy": 42
      },
      "core": {
        "source": "frame",
        "cx": 50.7,
        "cy": 40.1
      },
      "quads": {
        "source": "frame",
        "cx": 50.7,
        "cy": 55.7
      },
      "calves": {
        "source": "frame",
        "cx": 50.2,
        "cy": 80.2
      }
    }
  },
  "male-back": {
    "width": 370,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "frame",
        "cx": 50,
        "cy": 22.9
      },
      "back": {
        "source": "frame",
        "cx": 49.9,
        "cy": 30.4
      },
      "triceps": {
        "source": "frame",
        "cx": 49.6,
        "cy": 32
      },
      "forearms": {
        "source": "frame",
        "cx": 50,
        "cy": 42.4
      },
      "glutes": {
        "source": "frame",
        "cx": 50,
        "cy": 48.4
      },
      "hamstrings": {
        "source": "frame",
        "cx": 50.1,
        "cy": 60.9
      },
      "calves": {
        "source": "frame",
        "cx": 50.4,
        "cy": 78.4
      }
    }
  },
  "female-front": {
    "width": 363,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "derived",
        "cx": 51.4,
        "cy": 24
      },
      "chest": {
        "source": "derived",
        "cx": 51.7,
        "cy": 25.6
      },
      "biceps": {
        "source": "frame",
        "cx": 51,
        "cy": 32.5
      },
      "forearms": {
        "source": "derived",
        "cx": 50.4,
        "cy": 42.4
      },
      "core": {
        "source": "derived",
        "cx": 51.1,
        "cy": 40.6
      },
      "quads": {
        "source": "frame",
        "cx": 51,
        "cy": 56.1
      },
      "calves": {
        "source": "derived",
        "cx": 50.8,
        "cy": 79.2
      }
    }
  },
  "female-back": {
    "width": 369,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "derived",
        "cx": 50.5,
        "cy": 23.7
      },
      "back": {
        "source": "derived",
        "cx": 50.4,
        "cy": 28.7
      },
      "triceps": {
        "source": "derived",
        "cx": 50.1,
        "cy": 32.6
      },
      "forearms": {
        "source": "derived",
        "cx": 50.8,
        "cy": 42.6
      },
      "glutes": {
        "source": "frame",
        "cx": 50,
        "cy": 48.2
      },
      "hamstrings": {
        "source": "frame",
        "cx": 49.9,
        "cy": 60.7
      },
      "calves": {
        "source": "derived",
        "cx": 50,
        "cy": 78.6
      }
    }
  },
  "andro-front": {
    "width": 401,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "frame",
        "cx": 49.8,
        "cy": 23
      },
      "chest": {
        "source": "derived",
        "cx": 49.9,
        "cy": 24.6
      },
      "biceps": {
        "source": "derived",
        "cx": 49.8,
        "cy": 32.1
      },
      "forearms": {
        "source": "derived",
        "cx": 49.9,
        "cy": 42.3
      },
      "core": {
        "source": "frame",
        "cx": 49.8,
        "cy": 40.3
      },
      "quads": {
        "source": "derived",
        "cx": 49.9,
        "cy": 55.7
      },
      "calves": {
        "source": "derived",
        "cx": 50,
        "cy": 79.9
      }
    }
  },
  "andro-back": {
    "width": 388,
    "height": 759,
    "zones": {
      "shoulders": {
        "source": "derived",
        "cx": 50.8,
        "cy": 23
      },
      "back": {
        "source": "frame",
        "cx": 50.8,
        "cy": 27.9
      },
      "triceps": {
        "source": "derived",
        "cx": 50.3,
        "cy": 32.1
      },
      "forearms": {
        "source": "derived",
        "cx": 50,
        "cy": 42.3
      },
      "glutes": {
        "source": "derived",
        "cx": 50.4,
        "cy": 48.3
      },
      "hamstrings": {
        "source": "derived",
        "cx": 50.3,
        "cy": 60.7
      },
      "calves": {
        "source": "frame",
        "cx": 50,
        "cy": 78.5
      }
    }
  }
};

/** Every zone traced by the developer rather than taken from a frame: for design review. */
export const DERIVED_BODY_ZONES: string[] = [
  "female-front/shoulders",
  "female-front/chest",
  "female-front/forearms",
  "female-front/core",
  "female-front/calves",
  "female-back/shoulders",
  "female-back/back",
  "female-back/triceps",
  "female-back/forearms",
  "female-back/calves",
  "andro-front/chest",
  "andro-front/biceps",
  "andro-front/forearms",
  "andro-front/quads",
  "andro-front/calves",
  "andro-back/shoulders",
  "andro-back/triceps",
  "andro-back/forearms",
  "andro-back/glutes",
  "andro-back/hamstrings"
];

export const zoneMaskUrl = (figure: FigureKey, zone: ZoneKey) => `/body/zones/${figure}-${zone}.png`;
